//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Trader.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.CarClasses = new HashSet<CarClass>();
        }
    
        public int carID { get; set; }
        public int userID { get; set; }
        public int engineID { get; set; }
        public int modelYear { get; set; }
        public string transmission { get; set; }
        public Nullable<bool> @new { get; set; }
        public string color { get; set; }
        public decimal cost { get; set; }
        public string location { get; set; }
        public int kilometer { get; set; }
        public System.DateTime listedDate { get; set; }
        public byte[] carImage { get; set; }
    
        public virtual ICollection<CarClass> CarClasses { get; set; }
        public virtual CarEngine CarEngine { get; set; }
        public virtual CarUser CarUser { get; set; }
    }
}
