//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Trader.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarClass
    {
        public int classID { get; set; }
        public int modelID { get; set; }
        public int carID { get; set; }
        public string @class { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual CarModel CarModel { get; set; }
    }
}
