//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Trader.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarMake
    {
        public CarMake()
        {
            this.CarModels = new HashSet<CarModel>();
        }
    
        public int makeID { get; set; }
        public string make { get; set; }
    
        public virtual ICollection<CarModel> CarModels { get; set; }
    }
}
