//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Trader.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarModel
    {
        public CarModel()
        {
            this.CarClasses = new HashSet<CarClass>();
        }
    
        public int modelID { get; set; }
        public int makeID { get; set; }
        public string model { get; set; }
    
        public virtual ICollection<CarClass> CarClasses { get; set; }
        public virtual CarMake CarMake { get; set; }
    }
}
